/**
 * For HTML-formatted Coq snippets created by coqdoc.
 * This reverses the modifications made during pretty-printing
 * to allow the text to be placed in an editor.
 */
export class Deprettify {
    static REPLACES : [RegExp, string][];
    /**
     * Extra rules for coqdoc output that pretty-prints ASCII notations
     * as Unicode without the page importing `Utf8`. Not applied by
     * default: stdpp/Iris define these symbols as real notations.
     * Software Foundations agents push them onto REPLACES.
     */
    static SF_REPLACES : [RegExp, string][];
    /**
     * Remove redundant leading and trailing newlines generated by coqdoc.
     * @param {HTMLElement} element 
     */
    static trim(element) {
        var c;
        if ((c = element.firstChild) && Deprettify.isWS(c))
            element.removeChild(c);
        if ((c = element.firstChild) && Deprettify.isBR(c))
            element.removeChild(c);
        //if ((c = element.firstChild) && Deprettify.isWS(c))
        //    element.removeChild(c);
        while ((c = element.lastChild) && 
                (Deprettify.isWS(c) || Deprettify.isBR(c)))
            element.removeChild(element.lastChild);
        return element;
    }

    /**
     * @param {ChildNode} node
     */
    static isWS(node) {
        return node.nodeType === Node.TEXT_NODE &&
               node.nodeValue.match(/^\s*\n$/);
    }

    /**
     * @param {ChildNode} node
     */
    static isBR(node) {
        return node.nodeType === Node.ELEMENT_NODE &&
               node.nodeName === 'BR';
    }

    /**
     * Translate back some unicode symbols to their original ASCII.
     * @param {string} text 
     */
    static cleanup(text) {
        for (let [re, s] of this.REPLACES) text = text.replace(re, s);
        return text.replace(/^\n/, '');
    }
}

/* Safari does not support static members? */
Deprettify.REPLACES = /** @type {[RegExp, string][]} */ ([
    [/\xa0/g, ' '], [/⇒/g, '=>'],   [/×/g, '*'],
    [/→/g, '->'],   [/←/g, '<-'],   [/¬/g, '~'],
    [/⊢/g, '|-'],   [/\n☐/g, ''],
    [/∃/g, 'exists']  /* because it is also a tactic... */
]);

/* LF/PLF define their own versions of these (for Imp), so they cannot be
 * global. Merged from the stock SF injector (∨ ∧ ↔ ≤ ≠ ∈, also used by
 * AUfunctionalprogramming/course-material) plus ∀ and ≥, which coqdoc
 * emits and which otherwise kill the lexer with "Undefined token". */
Deprettify.SF_REPLACES = /** @type {[RegExp, string][]} */ ([
    [/∨/g, '\\/'], [/∧/g, '/\\'], [/↔/g, '<->'], [/≤/g, '<='], [/≠/g, '<>'],
    [/∈/g, '\\in'], [/∀/g, 'forall'], [/≥/g, '>=']
]);

// Local Variables:
// js-indent-level: 4
// End:
