name: JsCoq's CI Action

on:
  push:
    branches:
    - 'v9.0'
    - 'v8.20'
    - 'v8.19'
    - 'v8.18'
    - 'v8.17\+lsp'
  pull_request:
    branches:
    - 'v9.0'
    - 'v8.20'
    - 'v8.19'
    - 'v8.18'
    - 'v8.17\+lsp'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        jscoq_arch: [32, 64]
    env:
      OPAMJOBS: "2"
      OPAMROOTISOK: "true"
      OPAMYES: "true"
      NJOBS: "2"
      JSCOQ_ARCH: ${{ matrix.jscoq_arch }}
      OPAM_LINUX_URL: https://github.com/ocaml/opam/releases/download/2.3.0/opam-2.3.0-x86_64-linux
      OPAM_MACOS_URL: https://github.com/ocaml/opam/releases/download/2.3.0/opam-2.3.0-x86_64-darwin
      WASI_SDK_URL: https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-12/wasi-sdk-12.0-linux.tar.gz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install apt dependencies
        run: |
          sudo apt-get install aptitude
          sudo dpkg --add-architecture i386
          sudo aptitude -o Acquire::Retries=30 update -q
          sudo aptitude -o Acquire::Retries=30 install gcc-multilib g++-multilib pkg-config libgmp-dev:i386 -y
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - name: OPAM Setup
        run: |
          sudo curl -sL $OPAM_LINUX_URL -o /usr/bin/opam &&
          sudo chmod 755 /usr/bin/opam
      - name: OCaml Setup
        run: |
          opam init -y --bare --disable-sandboxing || true
          eval $(opam env)
          ./etc/toolchain-setup.sh --"$JSCOQ_ARCH"
          opam switch
          opam list
          opam config var root
      - name: WASI Setup
        run: |
          wget --quiet -O/tmp/wasi-sdk.tar.gz ${WASI_SDK_URL}
          ( cd /opt && sudo tar xf /tmp/wasi-sdk.tar.gz && sudo ln -s wasi-sdk-* wasi-sdk )
      - name: Coq build
        run: |
          echo 'Using Node.js:' && node --version
          set -e
          echo 'Building Coq...' # && echo -en 'travis_fold:start:coq.build\\r'
          make coq-get
          # echo -en 'travis_fold:end:coq.build\\r'
      - name: jsCoq build (JSOO)
        run: |
          set -e
          echo 'Building JsCoq (JSOO)...'
          make jscoq
      - name: jsCoq build (WASM)
        run: |
          set -e
          echo 'Building JsCoq (WACOQ)...'
          make wacoq
      - name: jsCoq addons
        run: |
          set -e
          echo 'Building addons disabled...'
          # echo 'Building Addons...'
          # EJGA: We need to resurrect this
          # make addons
      - name: jsCoq test
        run: |
          set -e
          echo 'Testing JsCoq disabled...'
          # EJGA: Disabled for now, we need to see how to update the CLI
          # npm install # EJGA: uggg, but otherwise this won't work.
          # make test
  docker:
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build (no push atm)
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: etc/docker/Dockerfile
          context: etc/docker
          target: jscoq-addons
          push: false
          tags: jscoq/jscoq:latest
          build-args: BRANCH=${{ env.BRANCH_NAME }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
